name: Build and Deploy

on:
  push:
    branches: [ Totest1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-output
          path: ${{github.workspace}}/aspnetapp/**

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy runs after build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ${{github.workspace}}
      
      - name: list
        run: |
           dir "${{github.workspace}}"
