name: Build and Deploy

on:
  push:
    branches: [ Totest1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-output-${{ github.run_number }}
          path: ${{github.workspace}}/aspnetapp/**

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy runs after build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v7
        with:
          name: build-output-${{ github.run_number }}
          path: ${{github.workspace}}/app
      
      - name: list
        run: |
           dir "${{github.workspace}}/app"

      - name: Notify team on success
        uses: JarvusInnovations/email-notify@v1
        with:
         to: mohanreddy072@gmail.com
         subject: 'Build/deploy success'
         body: 'Check the run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
